import { Area } from "../model/hint";
import { Item, PartType, Size } from "../scheme";

export interface IAreaDivider {
    /**
     * Divide the given Area according to a series of Item.
     * @param area, the Area need be divided.
     * @param item, the item which would divide the Area.
     * @return the small Areas generated by division algorithm.
     */
    divide(area: Area, item: Item): Array<Area>;
}

export interface IAreaFilter {
    /**
     * Check whether the area is available for the part of which size is partSize.
     * @param area, the area need check.
     * @param partType, the part type.
     * @param partSize, the size of part.
     * @return true, if it's good for the part; otherwise, false.
     */
    doFilter(area: Area, partType: PartType, partSize: Size): boolean;
}
